<?php

namespace App\Services\TestGeneration;

use App\Services\AI\AIProviderService;
use App\Services\WordPress\PluginAnalysisService;
use Illuminate\Support\Facades\Log;

class TestGenerationService
{
    private AIProviderService $aiService;
    private PluginAnalysisService $analysisService;
    private array $config;

    public function __construct(
        AIProviderService $aiService,
        PluginAnalysisService $analysisService
    ) {
        $this->aiService = $aiService;
        $this->analysisService = $analysisService;
        $this->config = config('thinktest_ai.test_generation');
    }

    /**
     * Generate comprehensive tests for WordPress plugin
     */
    public function generateTests(string $pluginCode, array $options = []): array
    {
        $framework = $options['framework'] ?? $this->config['default_framework'];
        $provider = $options['provider'] ?? 'openai';

        Log::info('Starting test generation', [
            'framework' => $framework,
            'provider' => $provider,
            'code_length' => strlen($pluginCode),
        ]);

        try {
            // First, analyze the plugin code
            $analysis = $this->analysisService->analyzePlugin($pluginCode, $options['filename'] ?? 'plugin.php');

            // Generate AI-powered tests
            $aiOptions = array_merge($options, [
                'framework' => $framework,
                'provider' => $provider,
                'analysis' => $analysis,
            ]);

            $aiResult = $this->aiService->generateWordPressTests($pluginCode, $aiOptions);

            // Post-process and enhance the generated tests
            $enhancedTests = $this->enhanceGeneratedTests($aiResult['generated_tests'], $analysis, $framework);

            // Generate additional test files if needed
            $testSuite = $this->buildTestSuite($enhancedTests, $analysis, $framework);

            return [
                'success' => true,
                'framework' => $framework,
                'provider' => $aiResult['provider'],
                'model' => $aiResult['model'],
                'analysis' => $analysis,
                'tests' => $testSuite,
                'main_test_file' => $enhancedTests,
                'usage' => $aiResult['usage'] ?? null,
            ];

        } catch (\Exception $e) {
            Log::error('Test generation failed', [
                'error' => $e->getMessage(),
                'framework' => $framework,
                'provider' => $provider,
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage(),
                'framework' => $framework,
                'provider' => $provider,
            ];
        }
    }

    /**
     * Enhance AI-generated tests with additional structure and best practices
     */
    private function enhanceGeneratedTests(string $generatedTests, array $analysis, string $framework): string
    {
        // Add proper file header
        $header = $this->generateTestFileHeader($analysis, $framework);
        
        // Clean up the generated tests
        $cleanedTests = $this->cleanupGeneratedTests($generatedTests);
        
        // Add setup and teardown methods if not present
        $enhancedTests = $this->addSetupTeardownMethods($cleanedTests, $analysis, $framework);
        
        // Add WordPress-specific test utilities
        $finalTests = $this->addWordPressTestUtilities($enhancedTests, $analysis, $framework);

        return $header . "\n\n" . $finalTests;
    }

    /**
     * Generate test file header with proper documentation
     */
    private function generateTestFileHeader(array $analysis, string $framework): string
    {
        $filename = $analysis['filename'] ?? 'plugin.php';
        $date = date('Y-m-d H:i:s');
        
        $header = "<?php\n";
        $header .= "/**\n";
        $header .= " * Generated Tests for WordPress Plugin: {$filename}\n";
        $header .= " * Generated by ThinkTest AI on {$date}\n";
        $header .= " * Framework: " . ucfirst($framework) . "\n";
        $header .= " * \n";
        $header .= " * This file contains comprehensive tests for the WordPress plugin.\n";
        $header .= " * Tests cover WordPress hooks, filters, functions, and security patterns.\n";
        $header .= " */\n";

        if ($framework === 'phpunit') {
            $header .= "\nuse PHPUnit\\Framework\\TestCase;";
            $header .= "\nuse WP_UnitTestCase;";
        } elseif ($framework === 'pest') {
            $header .= "\nuses(WP_UnitTestCase::class);";
        }

        return $header;
    }

    /**
     * Clean up AI-generated tests
     */
    private function cleanupGeneratedTests(string $tests): string
    {
        // Remove duplicate PHP opening tags
        $tests = preg_replace('/^<\?php\s*/', '', $tests);
        
        // Remove multiple consecutive empty lines
        $tests = preg_replace('/\n\s*\n\s*\n/', "\n\n", $tests);
        
        // Ensure proper indentation
        $lines = explode("\n", $tests);
        $cleanedLines = [];
        
        foreach ($lines as $line) {
            // Basic indentation cleanup
            $cleanedLines[] = $line;
        }
        
        return implode("\n", $cleanedLines);
    }

    /**
     * Add setup and teardown methods if not present
     */
    private function addSetupTeardownMethods(string $tests, array $analysis, string $framework): string
    {
        $hasSetup = strpos($tests, 'setUp') !== false;
        $hasTearDown = strpos($tests, 'tearDown') !== false;

        if ($framework === 'phpunit' && (!$hasSetup || !$hasTearDown)) {
            $setupTeardown = "\n";
            
            if (!$hasSetup) {
                $setupTeardown .= "    protected function setUp(): void\n";
                $setupTeardown .= "    {\n";
                $setupTeardown .= "        parent::setUp();\n";
                $setupTeardown .= "        // Initialize WordPress test environment\n";
                $setupTeardown .= "        \$this->factory = new WP_UnitTest_Factory();\n";
                $setupTeardown .= "    }\n\n";
            }
            
            if (!$hasTearDown) {
                $setupTeardown .= "    protected function tearDown(): void\n";
                $setupTeardown .= "    {\n";
                $setupTeardown .= "        // Clean up after tests\n";
                $setupTeardown .= "        parent::tearDown();\n";
                $setupTeardown .= "    }\n";
            }

            // Insert after class declaration
            $tests = preg_replace('/class\s+\w+\s+extends\s+\w+\s*\{/', '$0' . $setupTeardown, $tests);
        }

        return $tests;
    }

    /**
     * Add WordPress-specific test utilities
     */
    private function addWordPressTestUtilities(string $tests, array $analysis, string $framework): string
    {
        $utilities = "";

        // Add helper methods for WordPress testing
        if (!empty($analysis['hooks']) || !empty($analysis['filters'])) {
            $utilities .= "\n    /**\n";
            $utilities .= "     * Helper method to test WordPress hooks\n";
            $utilities .= "     */\n";
            $utilities .= "    protected function assertHookExists(\$hook, \$priority = 10)\n";
            $utilities .= "    {\n";
            $utilities .= "        \$this->assertTrue(has_action(\$hook), \"Hook {\$hook} should be registered\");\n";
            $utilities .= "    }\n\n";
        }

        if (!empty($analysis['database_operations'])) {
            $utilities .= "    /**\n";
            $utilities .= "     * Helper method to test database operations\n";
            $utilities .= "     */\n";
            $utilities .= "    protected function assertOptionExists(\$option_name)\n";
            $utilities .= "    {\n";
            $utilities .= "        \$this->assertNotFalse(get_option(\$option_name), \"Option {\$option_name} should exist\");\n";
            $utilities .= "    }\n\n";
        }

        if (!empty($utilities)) {
            // Insert before the last closing brace
            $tests = preg_replace('/\}(\s*)$/', $utilities . '}$1', $tests);
        }

        return $tests;
    }

    /**
     * Build complete test suite with multiple files if needed
     */
    private function buildTestSuite(string $mainTests, array $analysis, string $framework): array
    {
        $testSuite = [
            'main' => [
                'filename' => 'PluginTest.php',
                'content' => $mainTests,
                'description' => 'Main plugin functionality tests',
            ],
        ];

        // Generate additional test files for complex plugins
        if (!empty($analysis['ajax_handlers'])) {
            $testSuite['ajax'] = [
                'filename' => 'AjaxTest.php',
                'content' => $this->generateAjaxTests($analysis['ajax_handlers'], $framework),
                'description' => 'AJAX handler tests',
            ];
        }

        if (!empty($analysis['rest_endpoints'])) {
            $testSuite['rest'] = [
                'filename' => 'RestApiTest.php',
                'content' => $this->generateRestApiTests($analysis['rest_endpoints'], $framework),
                'description' => 'REST API endpoint tests',
            ];
        }

        if (!empty($analysis['security_patterns'])) {
            $testSuite['security'] = [
                'filename' => 'SecurityTest.php',
                'content' => $this->generateSecurityTests($analysis['security_patterns'], $framework),
                'description' => 'Security and sanitization tests',
            ];
        }

        return $testSuite;
    }

    /**
     * Generate AJAX-specific tests
     */
    private function generateAjaxTests(array $ajaxHandlers, string $framework): string
    {
        $tests = $this->generateTestFileHeader(['filename' => 'AJAX Handlers'], $framework);
        
        $tests .= "\n\nclass AjaxTest extends WP_UnitTestCase\n{\n";
        $tests .= "    public function test_ajax_handlers_registered()\n";
        $tests .= "    {\n";
        $tests .= "        // Test that AJAX handlers are properly registered\n";
        $tests .= "        \$this->assertTrue(true); // Placeholder\n";
        $tests .= "    }\n";
        $tests .= "}\n";

        return $tests;
    }

    /**
     * Generate REST API tests
     */
    private function generateRestApiTests(array $restEndpoints, string $framework): string
    {
        $tests = $this->generateTestFileHeader(['filename' => 'REST API'], $framework);
        
        $tests .= "\n\nclass RestApiTest extends WP_UnitTestCase\n{\n";
        $tests .= "    public function test_rest_endpoints_registered()\n";
        $tests .= "    {\n";
        $tests .= "        // Test that REST endpoints are properly registered\n";
        $tests .= "        \$this->assertTrue(true); // Placeholder\n";
        $tests .= "    }\n";
        $tests .= "}\n";

        return $tests;
    }

    /**
     * Generate security tests
     */
    private function generateSecurityTests(array $securityPatterns, string $framework): string
    {
        $tests = $this->generateTestFileHeader(['filename' => 'Security'], $framework);
        
        $tests .= "\n\nclass SecurityTest extends WP_UnitTestCase\n{\n";
        $tests .= "    public function test_input_sanitization()\n";
        $tests .= "    {\n";
        $tests .= "        // Test that user inputs are properly sanitized\n";
        $tests .= "        \$this->assertTrue(true); // Placeholder\n";
        $tests .= "    }\n";
        $tests .= "}\n";

        return $tests;
    }

    /**
     * Get supported frameworks
     */
    public function getSupportedFrameworks(): array
    {
        return $this->config['output_formats'];
    }

    /**
     * Validate test generation options
     */
    public function validateOptions(array $options): array
    {
        $errors = [];

        if (isset($options['framework']) && !array_key_exists($options['framework'], $this->config['output_formats'])) {
            $errors[] = 'Unsupported test framework: ' . $options['framework'];
        }

        if (isset($options['provider']) && !in_array($options['provider'], ['openai', 'anthropic'])) {
            $errors[] = 'Unsupported AI provider: ' . $options['provider'];
        }

        return $errors;
    }
}
